apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "helm.fullname" . }}
  labels:
    {{- include "helm.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "helm.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "helm.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort}}
#          livenessProbe:
#            httpGet:
#              path: {{ .Values.livenessProbe.httpGet.path}}
#              port: {{ .Values.livenessProbe.httpGet.port}}
#          readinessProbe:
#            httpGet:
#              path: {{ .Values.readinessProbe.httpGet.path}}
#              port: {{ .Values.readinessProbe.httpGet.port}}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}