apiVersion: v1
kind: Service
metadata:
  name: springboot-k8s-service
  labels:
    name: springboot-k8s
spec:
  ports:
    - nodePort: 31875
      port: 6060
      targetPort: 6060
      protocol: TCP
  selector:
    app: springboot-k8s
  type: LoadBalancer