server:
  port : 6060
  servlet:
    context-path: /ted

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/app_db
    username: root
    password: ushan
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true