spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/car_db
    username: postgres
    password: ushan
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true