server:
  port: 8082
  session:
    cookie: UISESSION
  servlet:
    context-path: /ui

security:
  oauth2:
    client:
      client-id: ClientId
      client-secret: secret
      access-token-uri: http://localhost:8081/auth/oauth/token
      user-authorization-uri: http://localhost:8081/auth/oauth/authorize
    resource:
      user-info-uri: http://localhost:8081/auth/rest/hello/principal

spring:
  thymeleaf:
    cache: false
